name = "Pervenience"
author = "neeleshpoli"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e69992ddbc2ef402e3ef84d7aca59e68685bd1a8d9df2301d1a959cd052d520"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
