name = "Pervenience"
author = "neeleshpoli"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b170cc9d92ffee9929042d00e1b176dc82274c1194cd4053363b80b26a079b"

[versions]
fabric = "0.19.2"
minecraft = "26.1"
